Apps/categorias/urls.py
from django.contrib import admin
from django.urls import path, include
from Apps.estudiantes import views
from .views import CategoriaView, CrearCatView, EditarCatView

app_name='categoria'
urlpatterns = [
    path('', CategoriaView.as_view(), name='categoria'),
    path('crear/', CrearCatView.as_view(), name='crearcat'),
    path('editar/ <int:pk>', EditarCatView.as_view(), name='editarcat'),
    #path('ver/ <int:pk>', VerDetailView.as_view(), name='ver'),

]

ExFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Apps.home.urls')),
    path('admin/', admin.site.urls),
    path('home/', include('Apps.home.urls', 'home')),
    path('estudiantes/', include('Apps.estudiantes.urls', 'estudiantes')),
    path('informacion/', include('Apps.informacion.urls', 'info')),
    path('categoria/', include('Apps.categorias.urls', 'categoria')),
    path('producto/', include('Apps.productos.urls', 'producto')),


 
]

Apps/categorias/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):

    nombre = models.CharField(
        max_length=100,
        unique=True,  
        verbose_name='Nombre de la Categoría'
    )
    descripcion = models.TextField(
        blank=True,    
        null=True,     
        verbose_name='Descripción'
    )
    
    activo = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'
        ordering = ['nombre'] 

    def __str__(self):
        return self.nombre

Apps/categorias/forms.py
from django import forms
from .models import Categoria

class CatForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = '__all__'

Apps/categorias/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, ListView, UpdateView, DetailView
from .models import Categoria
from django.urls import reverse_lazy
from .forms import CatForm
# Create your views here.

class CategoriaView(ListView): 
    model = Categoria
    template_name = 'categorias.html'
    context_object_name = 'lista_categorias'



class CrearCatView(CreateView):
    template_name = 'crearcat.html'
    form_class = CatForm
    success_url = reverse_lazy('categoria:categoria')


class EditarCatView(UpdateView):
    template_name = 'editarcat.html'
    model = Categoria
    form_class = CatForm
    success_url = reverse_lazy('categoria:categoria')

Apps/categorias/templates/categorias.html
{% extends 'base.html' %}

{% block contenido %}

<h2>LISTADO DE CATEGORIAS</h2>
<table class="table" border="1">
    <thead>
        <tr>
            <th>NOMBRE</th>
            <th>Descripcion</th>
            <th>Activo</th>
            <th>ACCIONES</th>
        </tr>
    </thead>
    <tbody>
        {% for cat in lista_categorias %}
        <tr>
            <td>{{ cat.nombre }}</td>
            <td>{{ cat.descripcion }}</td>
            <td>{{ cat.activo }}</td>


            <td>  
                <a href="{% url 'categoria:editarcat' cat.id %}" class="btn btn-warning">EDITAR</a>

            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<h2>CREAR CATEGORIAS ACA</h2>
<a href="{% url 'categoria:crearcat' %}" class="btn btn-success">CREAR</a>
{% endblock %}

Apps/categorias/templates/crearcat.html
{% extends 'base.html' %}
{% block contenido %}

<h1>Crear Categoria</h1>
    <form method="post">
        {% csrf_token %}
        Nombre {{ form.nombre }}
        descripcion {{ form.descripcion }}
        activo {{ form.activo }}
        <input type="submit" name="GUARDAR">
    </form>

    <a href="{% url 'categoria:categoria' %}">VER LISTA DE CATEGORIAS</a>

    
{% endblock %}

Apps/categorias/templates/editarcat.html
{% extends 'base.html' %}
{% block contenido %}

<h1>Editar Categoria</h1>
    <form method="post">
        {% csrf_token %}
        Nombre {{ form.nombre }}
        Descripcion {{ form.descripcion }}
        Activo {{ form.activo }}
        <input type="submit" name="GUARDAR">
    </form>

    <a href="{% url 'categoria:categoria' %}">VOLVER A LA LISTA DE CATEGORIAS</a>

    
{% endblock %}