Apps/productos/urls.py
from django.contrib import admin
from django.urls import path, include
from Apps.estudiantes import views
from .views import ProductoListView, CrearProdView, EditarProdView

app_name='producto'
urlpatterns = [
    path('', ProductoListView.as_view(), name='producto'),
    path('crear/', CrearProdView.as_view(), name='crearprod'),
    path('editar/ <int:pk>', EditarProdView.as_view(), name='editarprod'),

]

ExFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Apps.home.urls')),
    path('admin/', admin.site.urls),
    path('home/', include('Apps.home.urls', 'home')),
    path('estudiantes/', include('Apps.estudiantes.urls', 'estudiantes')),
    path('informacion/', include('Apps.informacion.urls', 'info')),
    path('categoria/', include('Apps.categorias.urls', 'categoria')),
    path('producto/', include('Apps.productos.urls', 'producto')),


 
]

Apps/productos/models.py
from django.db import models

# Create your models here.

class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField(null=True, blank=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField(default=0)
    
    categoria = models.ForeignKey(
        'categorias.Categoria', 
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

    def __str__(self):
        return self.nombre

Apps/productos/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'

Apps/productos/views.py
from django.views.generic import ListView, CreateView, UpdateView
from .forms import ProductoForm
from django.urls import reverse_lazy
from .models import Producto

class ProductoListView(ListView):
    model = Producto
    template_name = 'productos_lista.html'
    context_object_name = 'lista_productos'

class CrearProdView(CreateView):
    template_name = 'crearprod.html'
    form_class = ProductoForm
    success_url = reverse_lazy('producto:producto')

class EditarProdView(UpdateView):
    template_name = 'editarprod.html'
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy('producto:producto')

Apps/productos/templates/crearprod.html
{% extends 'base.html' %}

{% block contenido %}

<h1>Crear Producto</h1>
    <form method="post">
        {% csrf_token %}
        
        Nombre: {{ form.nombre }}
        <br>
        Descripción: {{ form.descripcion }}
        <br>
        Precio: {{ form.precio }}
        <br>
        Stock: {{ form.stock }}
        <br>
        
        Categoría: {{ form.categoria }}
        <br>
        
        <input type="submit" value="GUARDAR">
    </form>

    <a href="{% url 'producto:producto' %}">VER LISTA DE PRODUCTOS</a>

{% endblock contenido %}

Apps/productos/templates/editarprod.html
{% extends 'base.html' %}

{% block contenido %}

<h1>Editar Producto</h1>
    <form method="post">
        {% csrf_token %}
        
        Nombre: {{ form.nombre }}
        <br>
        Descripción: {{ form.descripcion }}
        <br>
        Precio: {{ form.precio }}
        <br>
        Stock: {{ form.stock }}
        <br>
        
        Categoría: {{ form.categoria }}
        <br>
        
        <input type="submit" value="GUARDAR">
    </form>

    <a href="{% url 'producto:producto' %}">VOLVER A LA LISTA DE PRODUCTOS</a>

{% endblock contenido %}

Apps/productos/templates/productos_lista.html
{% extends 'base.html' %}

{% block contenido %}

<h2>LISTADO DE PRODUCTOS</h2>
<table class="table" border="1">
    <thead>
        <tr>
            <th>NOMBRE</th>
            <th>DESCRIPCION</th>
            <th>PRECIO</th>
            <th>STOCK</th>
            <th>CATEGORÍA</th>
            <th>ACCIONES</th>
        </tr>
    </thead>
    <tbody>
        {% for prod in lista_productos %}
        <tr>
            <td>{{ prod.nombre }}</td>
            <td>{{ prod.descripcion }}</td>  <td>${{ prod.precio }}</td>    <td>{{ prod.stock }}</td>
            
            <td>{{ prod.categoria.nombre }}</td>
            
            <td>  
                <a href="{% url 'producto:editarprod' prod.id %}" class="btn btn-warning">EDITAR</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="7">No se encontraron productos registrados.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<h2>CREAR PRODUCTO AQUÍ</h2>
<a href="{% url 'producto:crearprod' %}" class="btn btn-success">CREAR</a>
{% endblock contenido %}