Apps/estudiantes/urls.py
from django.contrib import admin
from django.urls import path, include
from Apps.estudiantes import views
from .views import EstuView, CrearEstudianteView, EditarEstudianteView

app_name='estudiantes'
urlpatterns = [
    path('', EstuView.as_view(), name='estuapp'),
    path('crear/', CrearEstudianteView.as_view(), name='crear'),
    path('editar/ <int:pk>', EditarEstudianteView.as_view(), name='editar'),

]

ExFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Apps.home.urls')),
    path('admin/', admin.site.urls),
    path('home/', include('Apps.home.urls', 'home')),
    path('estudiantes/', include('Apps.estudiantes.urls', 'estudiantes')),
    path('informacion/', include('Apps.informacion.urls', 'info')),
    path('categoria/', include('Apps.categorias.urls', 'categoria')),
    path('producto/', include('Apps.productos.urls', 'producto')),


 
]

Apps/estudiantes/models.py
from django.db import models

class Estudiante(models.Model):
	nombre = models.CharField(max_length=100)
	apellido= models.CharField(max_length=100)
	creacion = models.DateTimeField(auto_now_add=True)

	def __str__(self):
        	return f"{self.nombre}"

Apps/estudiantes/forms.py
from django import forms
from .models import Estudiante

class EstudianteForm(forms.ModelForm):
    class Meta:
        model = Estudiante
        fields = '__all__'

Apps/estudiantes/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, ListView, UpdateView, DetailView
from .models import Estudiante
from django.urls import reverse_lazy
from .forms import EstudianteForm

class EstuView(ListView): 
    model = Estudiante
    template_name = 'estudiantes.html'
    context_object_name = 'lista_estudiantes'

    def get_queryset(self):
        vNombre = self.request.GET.get('NOMBRE')
        if(vNombre):
            return Estudiante.objects.filter(nombre__icontains=vNombre)
        else:
            return Estudiante.objects.all()


class CrearEstudianteView(CreateView):
    template_name = 'crear.html'
    form_class = EstudianteForm
    success_url = reverse_lazy('estudiantes:estuapp')


class EditarEstudianteView(UpdateView):
    template_name = 'editar.html'
    model = Estudiante
    form_class = EstudianteForm
    success_url = reverse_lazy('estudiantes:estuapp')

class VerDetailView(DetailView):
    model = Estudiante
    template_name = 'ver.html'

Apps/estudiantes/templates/crear.html
{% extends 'base.html' %}
{% block contenido %}

<h1>Crear Estudiante</h1>
    <form method="post">
        {% csrf_token %}
        Nombre {{ form.nombre }}
        Apellido {{ form.apellido }}
        <input type="submit" name="GUARDAR">
    </form>

    <a href="{% url 'estudiantes:estuapp' %}">VER LISTA DE ESTUDIANTES</a>

    
{% endblock %}

Apps/estudiantes/templates/editar.html
{% extends 'base.html' %}
{% block contenido %}

<h1>Editar Estudiante</h1>
    <form method="post">
        {% csrf_token %}
        Nombre {{ form.nombre }}
        Apellido {{ form.apellido }}
        <input type="submit" name="GUARDAR">
    </form>

    <a href="{% url 'estudiantes:estuapp' %}">VOLVER A LA LISTA DE ESTUDIANTES</a>

    
{% endblock %}

Apps/estudiantes/templates/estudiantes.html
{% extends 'base.html' %}

{% block contenido %}

<form method="get">
<input type="text" name="NOMBRE" value="{{request.GET.NOMBRE}}">
<button type="submit">BUSCAR</button>
</form>

<h2>LISTADO DE ESTUDIANTES</h2>
<table class="table" border="1">
    <thead>
        <tr>
            <th>NOMBRE</th>
            <th>EDAD</th>
            <th>ACCIONES</th>
        </tr>
    </thead>
    <tbody>
        {% for estudiante in lista_estudiantes %}
        <tr>
            <td>{{ estudiante.nombre }}</td>
            <td>{{ estudiante.apellido }}</td>

            <td>
                <a href="{% url 'estudiantes:editar' estudiante.id %}" class="btn btn-warning">EDITAR</a>
                <a href="{% url 'estudiantes:ver' estudiante.pk %}" class="btn btn-info">VER</a>
                
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<h2>CREAR ESTUDIANTE ACA</h2>
<a href="{% url 'estudiantes:crear' %}" class="btn btn-success">CREAR</a>
{% endblock %}

Apps/estudiantes/templates/ver.html
{% extends 'base.html' %}

{% block contenido %}
<h1>Detalles del Estudiante</h1>
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Nombre: {{ object.nombre }}</h5>
        <p class="card-text"><strong>Apellido:</strong> {{ object.apellido }}</p>
        <p class="card-text"><strong>Fecha de Creación:</strong> {{ object.creacion|date:"d/m/Y H:i" }}</p>
        <a href="{% url 'estudiantes:estuapp' %}" class="btn btn-primary">Volver al Listado</a>
    </div>
</div>
{% endblock %}